### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by Midnighter** [SegataLab/export2graphlan#1]
Hi,

From your requirements list it is not immediately obvious why `export2graphlan` should be Python 2.7 only. Could you comment on that? I'd be happy to submit a patch that makes it 2&3 compatible.

**Comment by fasnicar** [comment]
Dear Moritz,

Many thanks for your offer, but the main restriction that ties export2graphlan to Python 2 is GraPhlAn.
GraPhlAn has not yet been migrated to Python 3, so there is no point in having GraPhlAn and export2graphlan based on different Python versions at the moment.


Best,
Francesco

**Comment by Midnighter** [comment]
Okay, that makes sense. I was asking because I'm actually trying to visualize some kraken2 output and convert the kraken output to BIOM format which I then convert with export2graphlan and it seems that the newer `biom-format` versions only support Python 3.

Since I run these as individual steps in a nextflow pipeline, having different Python versions for the data conversion and the image drawing later would not be a problem. That said, I now have a conda Python 2.7 environment with everything installed just fine. I previously tried with biocontainers and that was problematic.

**Comment by jorondo1** [comment]
As of today I assume GraphLan is working since I managed to install it on python 3.9. Is  export2graphlan now compatible as well? I am quite new to this, following the metaphlan tutorial both install don't work; however, graphlan did using $ git clone https://github.com/biobakery/graphlan.git

Thanks

**Comment by fasnicar** [comment]
Hi, we actually did not migrate export2graphlan to Python 3, while GraPhlAn is now Python 3 compatible, sorry about this. It is on our todo list, but not with a very high priority at the moment. If you could manage to get it running into a separate environment running Python 2.7 would be great. Otherwise, I'll try to give you a timeline about when we could be able to have it migrated as well.

Many thanks,
Francesco

**Comment by jorondo1** [comment]
thanks a lot for the quick reply. Running it on python 2.7 shouldn't be a problem. I would still be curious to know around when the migration would be done if you have any idea. 

Cheers !
